### ISSUE TITLE
没效果

### ISSUE THREAD

**Issue by imohuan** [stefan-hui/rollup-plugin-monaco-editor-nls#1]
当前使用的是Vite + vue3，添加配置后没有相应的效果
https://cn.vitejs.dev/config/#optimizedeps-esbuildoptions

**Comment by stefan-hui** [comment]
我试了下 monaco版本太高会有问题，可以先降低一下版本   0.23.0没问题。
高版本我有时间了优化一下。

**Comment by npmrun** [comment]
@stefan-hui 你好，有任何进展吗，高版本的没啥用啊，我对这个不太熟，改不动
